### ISSUE TITLE
Liquid/Lava is broken in Marathon RED

### ISSUE THREAD

**Issue by riktoi** [treellama/scenario-utilities#1]
Lava in the level Jägermeister's Nightmare does not deal damage to the player and flashes the screen in a neon green instead of the expected orange/brown color.

Reference: [Video by Highyena showing the correct color and functionality](https://youtu.be/LQuUEznBoxE?t=610)

Attached: Current behaviour **(EPILEPSY WARNING!)**

https://github.com/treellama/scenario-utilities/assets/109578441/7bfa0679-3999-483c-811e-25e395bd2ec2

**Comment by treellama** [comment]
It is broken, but the functionality in the video you linked is not correct either! Playing the original RED and jumping in the lava on that level results in no damage taken, and no screen flashes!
